### ISSUE TITLE
Error cordova building with barcodescanner

### ISSUE THREAD

**Issue by mrbinr** [phonegap/phonegap-plugin-barcodescanner#22] opened 2015-07-02 20:35 UTC
Hi,
I'm trying to use phonegap-plugin-barcodescanner, i install it with the command line :
cordova plugin add com.phonegap.plugins.barcodescanner

and it works without problem, but when i try to build my project i have this error : 
:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/home/pascall/www/android/android-sdk-linux/build-tools/22.0.1/aapt package -f --no-crunch -I /home/pascall/www/android/android-sdk-linux/platforms/android-22/android.jar -M /.........../platforms/android/build/intermediates/manifests/full/debug/AndroidManifest.xml -S /.........../platforms/android/build/intermediates/res/debug -A /.........../platforms/android/build/intermediates/assets/debug -m -J /.........../platforms/android/build/generated/source/r/debug -F /.........../platforms/android/build/intermediates/res/resources-debug.ap_ --debug-mode --custom-package io.cordova.hellocordova -0 apk --output-text-symbols /.........../platforms/android/build/intermediates/symbols/debug
  Error Code:
  	132

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 43.013 secs

/.........../platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /.........../platforms/android/gradlew with args: cdvBuildDebug,-b,/.........../platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /.........../platforms/android/cordova/build: Command failed with exit code 8
You may not have the required environment or OS to build this project
Error: /.........../platforms/android/cordova/build: Command failed with exit code 8
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Process.ChildProcess._handle.onexit (child_process.js:802:5)

any idea ?

Thanks for your help
Best Regards 
Pascall

**Comment by surajpindoria** [comment] 2015-08-10 17:58
Hi @mrbinr, are you still seeing? I tried using the same command as you and was unable to reproduce the issue. Also, "com.phonegap.plugins.barcodescanner" is the old plugin name. The new version is now called "phonegap-plugins-barcodescanner". If you are still seeing the issue try installing using the new plugin name.

**Comment by mrbinr** [comment] 2015-08-12 11:50
Thanks for your answer, i gonna try it and will give you the feedback

Best Regards
Pascall

**Comment by sarangan12** [comment] 2016-05-05 23:29
No movement in about a year. Closing this issue

**Closed by sarangan12** 2016-05-05 23:29 UTC
Labels: bug

**Comment by daviddguedes** [comment] 2016-06-24 14:55
i am trying to build o ionic android app but i don't have success. The return in my terminal is this bellow:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 24.663 secs
Error: Error code 1 for command: /path/to/app/platforms/android/gradlew with args: cdvBuildDebug,-b,/path/to/app/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true

Someone can help me?
