### ISSUE TITLE
Automatically close the scan window

### ISSUE THREAD

**Issue by shanghaiyangming** [phonegap/phonegap-plugin-barcodescanner#483] opened 2017-06-12 07:31 UTC
The tool is very easy to use, but I encountered a practical problem, because my device is put in the store for the user practical, if the user points after the scan page does not do anything, it will cause the interface has been stuck in the sweep Code page, and will not automatically return to the normal guide page, how can I solve this problem?

**Comment by jcesarmobile** [comment] 2017-06-12 11:16
It's not clear what you are asking

**Comment by zoftc** [comment] 2017-06-14 10:27
I have the same problem, too.

Can the scanner be dismissed automatically after a idle time ?

**Comment by EddyVerbruggen** [comment] 2017-06-14 11:22
Isn't there a close function you can call after a certain JS timeout?

**Comment by jcesarmobile** [comment] 2017-06-14 11:27
No, but this issue is a duplicate of https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/430, closing

**Closed by jcesarmobile** 2017-06-14 11:27 UTC

**Comment by EddyVerbruggen** [comment] 2017-06-14 11:36
Oh, confused with the NativeScript version. That's where I added it to support continuous scanning more easily. We could add it here for iOS and Android.

**Comment by jcesarmobile** [comment] 2017-06-14 11:58
Yes, we should add it
