### ISSUE TITLE
Windows 10(m) / Windows 10: Crash / Freeze when opening BarcodeScanner with Access violation-Message

### ISSUE THREAD

**Issue by Fuchur84** [phonegap/phonegap-plugin-barcodescanner#544] opened 2017-09-17 11:38 UTC
Hi,

with the new update of W10(m) if I start the barcode scanner, it will close the app immediately. Debugger shows (after it notices, that for instance app on the smartphone is no longer running):
The program "[13216] WWAHost.exe" has been closed with the code -1073741819 (0xc0000005) 'Access violation'.
(translation of this: Das Programm "[13216] WWAHost.exe" wurde mit Code -1073741819 (0xc0000005) 'Access violation' beendet.)

Any idea what is going on there? I do not get any other information about the crash.
It worked before (still runs on for instance build 14393.1066 (still have a smartphone on that build and it works there) and I am quite sure it runs on 15063.540 (it still ran a two weeks ago)) but very likely after the last update to build 15063.608 it seems to be a problem.

Best regards and thank you very much for looking into it in advance :).
Fuchur

PS: And of cause: Thanks a lot for this very cool plugin :).

**Comment by thomasouvre** [comment] 2017-09-19 13:56
Hi,

I have the same problem. My OS Build is the following : 15063.608 too. It worked before.
I have an exception in the Windows.Medial.dll (access violation reading location).

Thank you for your plugin and for your help !

**Comment by Ponsen** [comment] 2017-09-19 14:48
I can verify it has something to do with the update to 15063.508
I've tested sereval PCs and tablets now and it's clear that the scanner is working before the latest patch. But I think the issue might be something deeper in the system itself, because now sometimes even the native camera app shows errors.

Here is the complete native output:

'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\DevDispItemProvider.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\DDORes.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\DDORes.dll'
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\DDORes.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\DefaultDeviceManager.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\WinMetadata\Windows.Media.winmd'. Module was built without symbols.
onecoreuap\inetcore\lib\scriptprojectionhost\scripthostcontext.cxx(427)\edgehtml.dll!0FA9E447: (caller: 043CAD15) LogHr(31) tid(3b78) 80000010 Name is an existing namespace rather than a typename.
onecoreuap\inetcore\lib\scriptprojectionhost\scripthostcontext.cxx(427)\edgehtml.dll!0FA9E447: (caller: 043CAD15) LogHr(32) tid(3b78) 80000010 Name is an existing namespace rather than a typename.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\Windows.Media.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\Windows.Media.dll'
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\Windows.Media.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\RTWorkQ.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\mfsensorgroup.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\mfsensorgroup.dll'
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\mfsensorgroup.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\mfplat.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\deviceaccess.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\deviceaccess.dll'
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\deviceaccess.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\MFCaptureEngine.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\MFCaptureEngine.dll'
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\MFCaptureEngine.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\mfcore.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\mfcore.dll'
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\mfcore.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ksuser.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\mfperfhelper.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\mfperfhelper.dll'
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\mfperfhelper.dll'. Cannot find or open the PDB file.
onecore\base\appmodel\runtime\winrt\lib\windows.applicationmodel.packagecataloglocalfactory.cpp(38)\Windows.ApplicationModel.dll!587C107C: (caller: 50876998) ReturnHr(1) tid(1b5c) 80070005 Access is denied.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\policymanager.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcp110_win.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\FSClient.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\FSClient.dll'
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\FSClient.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\avrt.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\vidcap.ax'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\vidcap.ax'
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\vidcap.ax'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\Kswdmcap.ax'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.15063.413_none_55bc94a37c2a2854\comctl32.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\mfc42.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\mfc42.dll'
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\mfc42.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\DextUVCB.ax'. Module was built without symbols.
'WWAHost.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\DextUVCB.ax'
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\DextUVCB.ax'. Module was built without symbols.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\Windows.Media.MediaControl.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\Windows.Media.MediaControl.dll'
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\Windows.Media.MediaControl.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\MMDevAPI.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\devobj.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\igdlh64.inf_amd64_134ba6ee926e8361\igd11dxva32.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\igdlh64.inf_amd64_134ba6ee926e8361\igd11dxva32.dll'
'WWAHost.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\igdlh64.inf_amd64_134ba6ee926e8361\igd11dxva32.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\setupapi.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\mfreadwrite.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\mfreadwrite.dll'
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\mfreadwrite.dll'. Cannot find or open the PDB file.
Exception thrown at 0x7502B832 (KernelBase.dll) in WWAHost.exe: 0x40080201: WinRT originate error (parameters: 0xC00D36B2, 0x0000002C, 0x1D57F144).
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\AudioSes.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\CoreMmRes.dll'. Module was built without symbols.
'WWAHost.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\CoreMmRes.dll'
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\CoreMmRes.dll'. Module was built without symbols.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\MFMediaEngine.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\MFMediaEngine.dll'
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\MFMediaEngine.dll'. Cannot find or open the PDB file.
onecoreuap\inetcore\lib\scriptprojectionhost\scripthostcontext.cxx(427)\edgehtml.dll!0FA9E447: (caller: 043CAD15) LogHr(33) tid(3b78) 80000010 Name is an existing namespace rather than a typename.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\CompPkgSup.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\CompPkgSup.dll'
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\CompPkgSup.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\Windows.Shell.ServiceHostBuilder.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\mfsvr.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\mfsvr.dll'
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\mfsvr.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvproc.dll'. Cannot find or open the PDB file.
'WWAHost.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\msvproc.dll'
'WWAHost.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvproc.dll'. Cannot find or open the PDB file.
Exception thrown at 0x1CFB5E14 (Windows.Media.dll) in WWAHost.exe: 0xC0000005: Access violation reading location 0x00000000.

**Comment by savs90** [comment] 2017-09-21 09:41
Same problem here after windows update

**Comment by DelemarreA** [comment] 2017-09-21 14:39
Same problem after the update of windows.... 
My OS Build : 15063.608

**Comment by arruix** [comment] 2017-09-22 21:46
Same issue here, please a fix or a workaround.
Windows OS build: 15063.608
Cordova platform windows: 5.0
Cordova version: 7.0.1

**Comment by ostara-dev** [comment] 2017-09-28 06:25
I get the same problem with an OS build of 15063.608
Is there any indication of a timescale for looking at a fix for this?

**Comment by savs90** [comment] 2017-09-28 06:57
OS build 15063.632 does not fix the problem either. The strange thing is that i have also camera plugin which is working , but the scanner is not. 
camera plugin -> cordova-plugin-camera 2.4.1 "Camera"

**Comment by ostara-dev** [comment] 2017-09-28 15:47
More info about this. There may be hope:

https://social.msdn.microsoft.com/Forums/en-US/601d9974-b184-4a36-a877-8a07d6787a94/uwpjs-all-javascript-apps-using-camera-preview-will-crash-after-latest-windows-update?forum=wpdevelop

**Comment by Fuchur84** [comment] 2017-10-02 23:08
@ostara-dev: Sounds good to me. Thanks for sharing. Maybe it will already be fixed in the next version (properply out tomorrow at patch tuesday... but this is only a guess).

**Comment by regnellr** [comment] 2017-10-19 12:23
It appears that this is corrected with Windows 10 Fall Creators Update - build 1709.

**Comment by khatridev** [comment] 2017-11-02 13:38
I have the same problem, while opening the front cam I see .net framework exception.
My OS version - Windows 10 Enterprise(1703). OS build: 15063.674
If it is regarding the update, let me know when the next update would come.

**Comment by bbosternak** [comment] 2017-11-03 09:29
@khatridev you can download the update manually from https://www.microsoft.com/en-us/software-download/windows10 It will fix this issue

**Comment by khatridev** [comment] 2017-11-07 06:13
I tried installing the upgrade but it gave me this error,

![err](https://user-images.githubusercontent.com/23520865/32479591-969704a2-c3b0-11e7-81f6-5fbe2e4ee6a6.PNG)

Looks like, Win 10 Enterprise needs some ISO file to update. May I know where can I get the ISO of the similar patch for Enterprise edition.

**Comment by stevesum** [comment] 2017-11-07 11:11
Some tests at Microsoft confirmed that the bug won't exist anymore at least
in Windows 10 pre-release build no. 16281.1000.

2017-11-07 7:13 GMT+01:00 khatridev <notifications@github.com>:

**Comment by khatridev** [comment] 2017-11-09 11:57
I still see the error in my build version

**Comment by Fuchur84** [comment] 2017-11-14 23:01
Win 10 (m) seems to work again too with the latest update released today. :)

**Comment by Fuchur84** [comment] 2017-11-14 23:03
Win 10(m) Build 15254.12.

**Comment by khatridev** [comment] 2017-11-16 07:27
I updated the build manually to 15063.726  by going through windows update settings, It does not crash now. Need to confirm if this issue persists in the higher build versions.

**Comment by spacepope** [comment] 2017-11-16 09:16
I also run into this issue (Windows 10 Version 1703) and the rolled out cumulative update 2017-11 (KB4048954) the bardcode scanner works again in a Windows UWP javascript app..

Windows 1703 Build Verison after Update: 15063.726

**Closed** 2018-06-14 19:47 UTC
Labels: windows, wontfix
