### ISSUE TITLE
Plugin sometimes refuses to scan on iOS, works after restarting app

### ISSUE THREAD

**Issue by mdailor** [phonegap/phonegap-plugin-barcodescanner#397] opened 2017-01-06 20:46 UTC
### Expected Behaviour
Using the front-facing camera, calling cordova.plugins.barcodeScanner.scan() displays the scanning screen, holding a QR code in front of the camera causes camera to scan the code and returns the data via the success callback.

### Actual Behaviour
Using the front-facing camera, calling cordova.plugins.barcodeScanner.scan() displays the scanning screen, holding a QR code in front of the camera does nothing. Clicking the cancel button causes the success callback to be called with result.cancelled set to true. Have to restart the app to get scanning to work again.

### Reproduce Scenario (including but not limited to)
Cannot reproduce this at will, seems to happen after some number of successful scans or x hours of operation.

#### Steps to Reproduce
Repeatedly call cordova.plugins.barcodeScanner.scan() and successfully scan a code, eventually it will stop scanning.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 9.3.5 on iPad5,4(iPad Air 2 16GB)

#### Cordova CLI version and cordova platform version
Cordova CLI 6.4.0
iOS platform 4.2.0

#### Plugin version
6.0.3

    cordova plugin version | grep phonegap-plugin-barcodescanner

#### Sample Code that illustrates the problem
getUserByIdScan: function (successCallback, errorCallback) {
	
    console.log("1. Called");
    console.log("2. Call cordova.plugins.barcodeScanner.scan()");
    cordova.plugins.barcodeScanner.scan(function (result) {
            
        console.log("3. Return cordova.plugins.barcodeScanner.scan() success");

		// User canceled scan?
		if (result.cancelled) {
			console.log("User canceled scan");
			errorCallback("Canceled");
			return;
		}
		
		// result.text contains our decoded data
		console.log("4. Content is '" + result.text + "'");

		successCallback(result.text);
	},
	function (errorMsg) {
		
		console.log("3b. Return cordova.plugins.barcodeScanner.scan() error: " + errorMsg);
		var msg = "ID scan failed: " + errorMsg;
		errorCallback(msg);
		return;
	},
	{
		"preferFrontCamera" : true, // iOS and Android
		"showFlipCameraButton" : false
	});
}

**Comment by uniphonic** [comment] 2017-01-12 21:22
I'm thinking this is probably the same as #370

**Comment by mdailor** [comment] 2017-01-12 21:32
Sure seems like!

**Comment by jcesarmobile** [comment] 2017-03-05 18:37
Closing as duplicate of https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/370

**Closed by jcesarmobile** 2017-03-05 18:37 UTC
