### ISSUE TITLE
Close scan on ios

### ISSUE THREAD

**Issue by mario-berardo** [phonegap/phonegap-plugin-barcodescanner#752] opened 2018-12-21 23:38 UTC
Hi, 
Very nice plugin.
Is There any way to close the plugin on ios ? Something like a "scanClose" function would be nice.

**Comment by jcesarmobile** [comment] 2018-12-21 23:42
Duplicate of 
https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/430

**Closed by jcesarmobile** 2018-12-21 23:42 UTC
