### ISSUE TITLE
After 60 scan, Bar code scan working stop

### ISSUE THREAD

**Issue by deepikajainvoloansys** [phonegap/phonegap-plugin-barcodescanner#575] opened 2017-11-14 10:36 UTC
When i start scan bar code it is working perfectly, but when i scan 60 bar code after it stop working.
after that i have to kill app and restart app again.

**Comment by lucasverra** [comment] 2017-11-16 11:01
provide more info please @deepikajainvoloansys

**Comment by jcesarmobile** [comment] 2017-11-16 11:09
Closing as duplicate of https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/370

**Closed by jcesarmobile** 2017-11-16 11:09 UTC
