### ISSUE TITLE
Windows 10 app crashes, when starting barcodescanner

### ISSUE THREAD

**Issue by als1979** [phonegap/phonegap-plugin-barcodescanner#360] opened 2016-11-08 04:50 UTC
### Expected Behaviour
Open plugin, get camera interface

### Actual Behaviour
App exits

#### Steps to Reproduce
install plugin and dependencies, and run basic sample

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
windows 10 --arch="x64" or --arch="x86"

#### Cordova CLI version and cordova platform version
Cordova CLI: 6.4.0
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
OS: win10
Node Version: v4.4.7

#### Plugin version
phonegap-plugin-barcodescanner 6.0.3 "BarcodeScanner"

#### Logs taken while reproducing problem
From visual studio 2015

'WWAHost.exe' (Script): Loaded 'Script Code (MSAppHost/3.0)'. 
Exception is about to be caught by JavaScript library code at line 542, column 17 in ms-appx-web://com.ionicframework.allan1875245/www/plugins/phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy.js
0x800a139e - JavaScript runtime error: NotFoundError

Hope you can help.

**Comment by daserge** [comment] 2016-11-08 09:19
@als1979 I confirm the bug - looks like the __cordova plugin add__ does not add the Webcam Capability to the Windows 10 manifest, investigating.
You can enable it manually in VS or directly in the package.windows10.appxmanifest for now:
```xml
  <Capabilities>
    <Capability Name="internetClient" />
    <DeviceCapability Name="webcam" />
  </Capabilities>
```

**Comment by als1979** [comment] 2016-11-08 09:29
That did the trick, thank you very much.

**Comment by daserge** [comment] 2016-11-08 09:31
Tracking the issue here:
https://issues.apache.org/jira/browse/CB-12124

**Comment by daserge** [comment] 2016-11-09 07:17
The issue is fixed in master and will be out with next cordova-windows release.

**Comment by nsteenbeek** [comment] 2017-02-14 11:12
Had same issue and just verified that cordova-windows 5.0.0 fixes the problem. Please check if config.xml has >= 5.0.0 in <engine name="windows" spec="~5.0.0" />.
@daserge This issue can be closed.

**Comment by daserge** [comment] 2017-02-14 12:09
Thanks @nsteenbeek !

**Closed by daserge** 2017-02-14 12:09 UTC
Labels: bug, windows
