### ISSUE TITLE
Camera overlay

### ISSUE THREAD

**Issue by thomas-tran** [phonegap/phonegap-plugin-barcodescanner#35] opened 2015-07-21 12:29 UTC
Hi,

I am just wondering whether this plug in can have the overlay layer on the camera. In my use case, I need to provide the custom text and a custom button when the camera open. How can I do it with this plug in.

Thanks
THomas

**Comment by jaredgreener** [comment] 2015-12-30 00:29
+1

**Comment by rwagnon** [comment] 2016-03-04 16:19
+1

**Comment by mrgcohen** [comment] 2017-01-08 03:36
+1

**Comment by lasseron** [comment] 2017-02-21 08:23
+1

**Comment by gaetansenn** [comment] 2017-06-19 10:39
+1

**Comment by nicks258** [comment] 2017-11-29 09:52
+1

**Comment by caroguerrero** [comment] 2018-01-13 17:37
+1

**Comment by jcesarmobile** [comment] 2018-04-28 22:26
Duplicate of #11

**Closed by jcesarmobile** 2018-04-28 22:26 UTC
Labels: enhancement, question
