### ISSUE TITLE
iOS10 scanning only first part of barcode

### ISSUE THREAD

**Issue by wilsoncmartins** [phonegap/phonegap-plugin-barcodescanner#339] opened 2016-10-07 15:46 UTC
Good morning,

I'm having a problem with barcode scan on iOS10,  i changed the plugin phonegap-plugin-barcodescanner in order to fix the memory leak, but happened this:
When I scan some bar, for exemple:
![image](https://cloud.githubusercontent.com/assets/15194075/19196152/c9a07d50-8c8a-11e6-82ed-1c0e6a88f11f.png)

using the puglin:
`<plugin name="phonegap-plugin-barcodescanner" version="6.0.2"  spec="https://github.com/jlowe234/phonegap-plugin-barcodescanner.git" />`
It scans: 42010010 (only the first part, and don't have memory leak)

using the plugin:
`<plugin name="phonegap-plugin-barcodescanner" version="6.0.2"  spec="https://github.com/phonegap/phonegap-plugin-barcodescanner.git" />`
It scans: 420100109261290100106971583637 (ok, but using this version i have problem if memory leak).

I would be grateful if you can help, thank you.

**Comment by jcesarmobile** [comment] 2016-10-08 15:13
So, your problem with this plugin is the memory leak. Then this issue is a duplicate of https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/312

For issues with a fork, report the problems to the fork's author

**Closed by jcesarmobile** 2016-10-08 15:13 UTC
