### ISSUE TITLE
Kindle Fire FireOS permissions issue with implied autofocus

### ISSUE THREAD

**Issue by viking2917** [phonegap/phonegap-plugin-barcodescanner#558] opened 2017-10-16 17:39 UTC
### Expected Behaviour

Applications built with this plugin should be supported on modern Kindle Fire FireOS tablets. 

### Actual Behaviour

I'm using the BarCode Scanner plugin and porting a working Android project to Kindle Fire (FireOS). When submitting to the Amazon store, their compatibility tester fails for most recent devices because it states that my manifest file requires the android.hardware.camera.autofocus permission, but that recent devices don't support that permission. So far as I can tell, the plugin does not specifically request this permission (it only requests Camera permission), however according to Android docs, the autofocus permission is "implied" by default when the camera permission is requested. (https://developer.android.com/guide/topics/manifest/uses-feature-element.html#permissions(https://developer.android.com/guide/topics/manifest/uses-feature-element.html#permissions))

I am working around this at present by manually adding 
(https://developer.android.com/guide/topics/manifest/uses-feature-element.html#permissions)
```
<config-file mode="merge" parent="/*" target="AndroidManifest.xml">
        <uses-feature android:name="android.hardware.camera.autofocus" android:required="false" />
    </config-file>
```
to my config.xml  file, but I'm wondering if the plugin itself should explicitly declare this permission not required, so that most recent Kindle Fire devices can be supported out of the box?

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Kindle Fire FireOS

#### Cordova CLI version and cordova platform version

    cordova --version
cordova --version
7.0.1

    cordova platforms
cordova platforms
Installed platforms:
  android 6.2.3
  ios 4.4.0
Available platforms: 
  blackberry10 ~3.8.0 (deprecated)
  browser ~4.1.0
  osx ~4.0.1
  webos ~3.7.0

#### Plugin version

   cordova plugin version | grep phonegap-plugin-barcodescanner
phonegap-plugin-barcodescanner 6.0.6 "BarcodeScanner"

**Comment by jcesarmobile** [comment] 2017-10-16 17:56
Closing as duplicate of https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/374

**Closed by jcesarmobile** 2017-10-16 17:56 UTC

**Comment by viking2917** [comment] 2017-10-16 18:39
@jcesarmobile thanks for catching that dupe, didn't see it.
