### ISSUE TITLE
Barcodescanner takes pictures loop - Windows Phone 8.1

### ISSUE THREAD

**Issue by sgo13** [phonegap/phonegap-plugin-barcodescanner#85] opened 2015-10-01 12:49 UTC
Hi,

I have a problem on Windows Phone 8.1, when I launch the scan function, the video preview is displayed and then it takes pictures in loop. I can hardly scan a barcode and my application crashes often.
Do you have any information about this problem ?
The problem occurs on Nokia Lumia 625 and 925 but NOT on Lumia 635 and 930...

Thank you for your help.

**Comment by ikermart** [comment] 2015-10-13 18:24
Same problem for me. It has also another problem it launches only with the front camera.

**Comment by pospa78** [comment] 2015-11-20 09:45
Hi,
I have same problem on Windows Phone 8.1 Nokia Lumia 520 with last OS version 8.10.14219.34, but Nokia Lumia 730 with older version 8.10.14167.221 works great.
I use Cordova version 5.4.0 and phonegap-plugin-barcodescanner 4.1.0

**Comment by vladimir-kotikov** [comment] 2015-12-23 11:14
@ikermart, switching to back camera added in d68cdce6f920c3db0bf7a1345f60a6fdabedde95

The problem in general is caused by abscence/breakage of corresponding APIs for Windows 8/8.1 and probably hardly ever will be resolved. Another possible reason is a bug in camera drivers on particular devices. I also can confirm that plugin crashes after some time on Lumia 520 but works fine on Lumia 730

Closing this as duplicate. For more details on isuse origin and workarounds refer to #55

**Closed by vladimir-kotikov** 2015-12-23 11:14 UTC
