### ISSUE TITLE
Question about Android barcode scanning behavior.

### ISSUE THREAD

**Issue by mamarkgp** [phonegap/phonegap-plugin-barcodescanner#728] opened 2018-10-22 06:32 UTC
Little background:

I implemented a continuos scanning on both iOS and Android scanning by iterating the scan if the scan is successful. For iOS, it is really smooth but on Android the business would like to skip the freeze part to show the scanned barcode and to just close the scanner instead and add the scanned barcode to the table.

How can I remove the freeze after the android scanner successfully scanned a barcode? 

Thanks, I will appreciate any help!

**Comment by jcesarmobile** [comment] 2018-10-29 16:09
Close as duplicate of https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/730

**Closed by jcesarmobile** 2018-10-29 16:09 UTC
