### ISSUE TITLE
IOS 9.3.5 + 9.3.4 crashes on click on camera symbol

### ISSUE THREAD

**Issue by vrt0r** [phonegap/phonegap-plugin-barcodescanner#324] opened 2016-09-06 09:26 UTC
Tested on IPad 3, IPhone  5s, IPhone SE and IPad Mini 2

**Comment by jcesarmobile** [comment] 2016-09-06 09:32
You mean the button to switch the camera from back to front?

**Comment by vrt0r** [comment] 2016-09-06 09:50
Im not sure (because it crashes) lower right corner there is an camera symbol. When i click on it, it crashes.

Im not sure if you have to click on the camera to take a photo to scan a code ? Because i tried with a lot of different codes and it never recognises any code. On Android it works perfect on all tested devices.
Thats why i thought the camera button is to take a photo and after that the photo is going to be scanned for a code.

**Comment by vrt0r** [comment] 2016-09-12 11:10
Ok in the Release , installed over Testflight the Button works, and it just switches the camera (front / back).
It crashed on all devices when i compile over VS2015 to the device.
But, no matter if it crashes or not, i was not able to scan any code.
I tested an QR Code and an different Barcodes.

**Comment by jcesarmobile** [comment] 2016-09-20 22:01
The camera button to switch cameras is not crashing anymore.
Tried "showFlipCameraButton": false and didn't show the button.
I've tried to scan 3 different bar codes and all of them worked, but it was a bit difficult, it took me a while with an iPod touch (not the better camera)
So I'm closing this issue because I couldn't reproduce the issues anymore and the problems scanning has been reported on other issues.

**Closed by jcesarmobile** 2016-09-20 22:01 UTC
