### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by riaz12s** [phonegap/phonegap-plugin-barcodescanner#227] opened 2016-05-09 18:41 UTC
Hi,

I think it would cool to have a **header** and **footer** setup when scanning a Barcode, maybe we could set HTML or Javascript in the header and footer.

Something like the attachment :)
![screenshot_2016-05-09-19-32-40 1](https://cloud.githubusercontent.com/assets/19173062/15123913/236ecb6a-1626-11e6-9a77-f21792d1a596.png)

**Comment by pke** [comment] 2016-06-20 10:48
It would be even nicer if we could specify where in the app the camera viewport should appear.

**Comment by macdonst** [comment] 2017-07-11 21:21
I consider this to be a duplicate of #11 and #35

**Closed by macdonst** 2017-07-11 21:21 UTC
Labels: duplicate
