### ISSUE TITLE
Problem with IOS 10.2

### ISSUE THREAD

**Issue by amerlin** [phonegap/phonegap-plugin-barcodescanner#407] opened 2017-01-26 18:16 UTC
Hi, I have a problem with phonegap-plugin-barcodescanner 6.0.5 "BarcodeScanner" with IOS 10.2.

In my application I have this code (from our site). 

 cordova.plugins.barcodeScanner.scan(
          function (result) {
            alert("We got a barcode\n" +
              "Result: " + result.text + "\n" +
              "Format: " + result.format + "\n" +
              "Cancelled: " + result.cancelled);
          },
          function (error) {
            alert("Scanning failed: " + error);
          },
          {
            preferFrontCamera: true, // iOS and Android 
            showFlipCameraButton: true, // iOS and Android 
            showTorchButton: true, // iOS and Android 
            torchOn: true, // Android, launch with the torch switched on (if available) 
            prompt: "Place a barcode inside the scan area", // Android 
            resultDisplayDuration: 500, // Android, display scanned text for X ms. 0 suppresses it entirely, default 1500 
            formats: "QR_CODE,PDF_417", // default: all but PDF_417 and RSS_EXPANDED 
            orientation: "landscape", // Android only (portrait|landscape), default unset so it rotates with the device 
            disableAnimations: true // iOS 
          }
        );

When I use Ionic View app this work fine. 
When I test with TestFligth not work, nothing appear.

Also try to create file ipa and install by itunes, but nothing.

Thanks

**Comment by muse109** [comment] 2017-01-28 23:07
I have the same problem,  my app is rejected Because nothing happends when the button to open the scanner is pushed,  help

**Comment by redfoxs111** [comment] 2017-01-30 04:49
i have the same problem. test on ionic view push scan 4 time. my app is close .

**Comment by macdonst** [comment] 2017-01-30 23:55
@amerlin it seems like the barcode scanner is not getting included in your app. Can you check to make sure that the file `./platforms/ios/Push151/Plugins/phonegap-plugin-barcodescanner/CDVBarcodeScanner.mm` exists?

**Comment by jcesarmobile** [comment] 2017-02-13 17:48
Do you have a Content-Security-Policy meta tag in your index.html?

If you have it, share it on the issue.

**Comment by arruix** [comment] 2017-02-22 22:12
I have a similar issue on iOS 10.1+ after try scan 4  to 7 times my app crash, the first and second time works fine, I tried with this options https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/312, but still have the issue

phonegap-plugin-barcodescanner: 6.0.5
iOS: 10.1, 10.2
Cordova: 6.0.4

**Comment by jcesarmobile** [comment] 2017-02-22 23:33
I don't see how that is similar to this issue

**Comment by arruix** [comment] 2017-02-24 16:56
I forget mention that my issue is very similar to @redfoxs111

**Comment by jcesarmobile** [comment] 2017-02-28 13:06
No answer after 15 days, closing issue.

This is probably caused by a Content-Security-Policy meta tag not having `gap:`

For the ones that it works but only a few times, there is another issue for that https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/370

**Closed by jcesarmobile** 2017-02-28 13:06 UTC
