### ISSUE TITLE
Unable to create ios build using ionic when barcodescanner plugin is used with cordova 8.0.0

### ISSUE THREAD

**Issue by abhiveeru85** [phonegap/phonegap-plugin-barcodescanner#591] opened 2018-01-08 05:01 UTC
#### Cordova CLI version and cordova platform version

    cordova --version
    cordova platforms

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner

**Comment by jpike88** [comment] 2018-01-08 07:37
This may be the fix:

https://github.com/streaka/phonegap-plugin-barcodescanner/commit/4e6a7063f5703d728827a8a03bf8d50ea38ea9c8

**Comment by jcesarmobile** [comment] 2018-01-08 10:17
Good catch @jpike88!

I've sent a PR (https://github.com/phonegap/phonegap-plugin-barcodescanner/pull/592)
But closing this issue as it's a duplicate of https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/589

**Closed by jcesarmobile** 2018-01-08 10:17 UTC
