### ISSUE TITLE
Hello, any one help me out on this.Can we add some UI on QR Scanner view like paytm i.e... in paytm we can enter number manually and we can scan QR Code also.

### ISSUE THREAD

**Issue by thejaa** [phonegap/phonegap-plugin-barcodescanner#791] opened 2019-06-03 10:00 UTC
#### Cordova CLI version and cordova platform version

    cordova --version
    cordova platforms

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner

**Comment by jcesarmobile** [comment] 2019-06-25 11:20
Closing as duplicate of https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/790

**Closed by jcesarmobile** 2019-06-25 11:20 UTC
