### ISSUE TITLE
Question about Android Barcode Scanning process

### ISSUE THREAD

**Issue by mamarkgp** [phonegap/phonegap-plugin-barcodescanner#729] opened 2018-10-22 06:59 UTC
**I dont need the issue format because this is only a question.**

Can I remove the freeze after successfully scanning a barcode in Android? And how?

Any help will be appreciated, Thanks!

#### Cordova CLI version and cordova platform version

    cordova --version
    cordova platforms

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner

**Comment by jcesarmobile** [comment] 2018-10-29 16:09
Close as duplicate of https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/730

**Closed by jcesarmobile** 2018-10-29 16:09 UTC
