### ISSUE TITLE
Any way to keep scanner open in iOS?

### ISSUE THREAD

**Issue by akeresztesgh** [phonegap/phonegap-plugin-barcodescanner#750] opened 2018-12-19 19:23 UTC
Hi,

First I would like to thank you for making such a nice plugin.  

Is there any way to keep the scanner open for "continuous scanning" in iOS?  My clients need to scan a lot of items at a time (qr codes) and having the screen close every after every scan takes too much time.  I'm not even sure if this is possible on iOS.

If this is possible, would it be difficult to implement?

Thanks!
AJ

**Comment by jcesarmobile** [comment] 2018-12-21 23:44
Duplicate of 
https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/69

**Closed by jcesarmobile** 2018-12-21 23:44 UTC
