### ISSUE TITLE
Overlay barcode scanner in ionic view

### ISSUE THREAD

**Issue by 1nfinite** [phonegap/phonegap-plugin-barcodescanner#409] opened 2017-02-04 05:25 UTC
I am having trouble on overlaying barcode scanner in ionic view. 

Eg: i have a `cordova-camera.html view` with a header bar.
What i intend to achieve is to have the barcode scanner to stay in the view (with the header bar visible).
But my actual outcome is the barcode scanner take up the entire view.

How can it be achieved?

**Comment by afeezaziz** [comment] 2017-02-28 12:57
Hi @1nfinite , I would like to clarify, are you looking for something that is similar to camera preview but instead of camera, is it barcode?

**Comment by jcesarmobile** [comment] 2017-02-28 13:02
Duplicate of https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/223

**Closed by jcesarmobile** 2017-02-28 13:02 UTC
