### ISSUE TITLE
Interleaved barcode 2 of 5 - Brazilian barcode type

### ISSUE THREAD

**Issue by embarbosa** [phonegap/phonegap-plugin-barcodescanner#354] opened 2016-11-02 14:46 UTC
Hello everyone.

I've been trying to use the plugin to read a barcode, but it is not working...
:(
I aim the red line to barcode, but nothing happens.

### Expected Behaviour
It is not reading the Barcode type - INTERLEAVED 2 of 5 (Brazilian type)

### Actual Behaviour
Trying to focus on the Barcode but it is not working 

### Reproduce Scenario (including but not limited to)
Try to use this bar code, please
![fullsizerender 1](https://cloud.githubusercontent.com/assets/4589788/19933060/513eb22c-a0f9-11e6-81da-af03423d29a2.jpg)

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
IOS 10

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
iPhone 6

#### Cordova CLI version and cordova platform version
    cordova --version
    6.2.0

    cordova platforms
Installed platforms:
  android 5.1.1
  ios 4.1.1
Available platforms: 
  amazon-fireos ~3.6.3 (deprecated)
  blackberry10 ~3.8.0
  browser ~4.1.0
  firefoxos ~3.6.3
  osx ~4.0.1
  webos ~3.7.0
#### Plugin version

phonegap-plugin-barcodescanner 6.0.3 "BarcodeScanner"

#### Sample Code that illustrates the problem
                cordova.plugins.barcodeScanner.scan(
                function (result) {
                    alert("We got a barcode\n" +
                        "Result: " + result.text + "\n" +
                        "Format: " + result.format + "\n" +
                        "Cancelled: " + result.cancelled);
                },
                function (error) {
                    alert("Scanning failed: " + error);
                },
                {
                    "preferFrontCamera": true, // iOS and Android
                    "showFlipCameraButton": true, // iOS and Android
                    "prompt": "Place a barcode inside the scan area", // supported on Android only
                }
            );

#### Logs taken while reproducing problem
2016-11-02 12:50:02.159856 barcodetest[3514:1560798] Apache Cordova native platform version 4.1.1 is starting.
2016-11-02 12:50:02.161775 barcodetest[3514:1560798] Multi-tasking -> Device: YES, App: YES
2016-11-02 12:50:02.518434 barcodetest[3514:1560798] Using UIWebView
2016-11-02 12:50:02.524511 barcodetest[3514:1560798] [CDVTimer][handleopenurl] 0.224054ms
2016-11-02 12:50:02.529302 barcodetest[3514:1560798] [CDVTimer][intentandnavigationfilter] 4.693985ms
2016-11-02 12:50:02.529457 barcodetest[3514:1560798] [CDVTimer][gesturehandler] 0.091016ms
2016-11-02 12:50:02.575545 barcodetest[3514:1560798] [CDVTimer][splashscreen] 46.023011ms
2016-11-02 12:50:02.608738 barcodetest[3514:1560798] [CDVTimer][statusbar] 32.999992ms
2016-11-02 12:50:02.611078 barcodetest[3514:1560798] [CDVTimer][keyboard] 2.216995ms
2016-11-02 12:50:02.611179 barcodetest[3514:1560798] [CDVTimer][TotalPluginStartup] 86.956024ms
2016-11-02 12:50:03.902947 barcodetest[3514:1560798] Resetting plugins due to page load.
2016-11-02 12:50:04.537298 barcodetest[3514:1560798] Finished load of: file:///var/containers/Bundle/Application/4DFD4761-D5B9-4EDC-AD39-F336254C76BA/barcodetest.app/www/index.html#/home
2016-11-02 12:50:04.924980 barcodetest[3514:1560798] THREAD WARNING: ['StatusBar'] took '30.640137' ms. Plugin should use a background thread.
2016-11-02 12:50:08.086210 barcodetest[3514:1560798] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2016-11-02 12:50:08.099180 barcodetest[3514:1560798] [MC] Reading from public effective user settings.
2016-11-02 12:50:08.152345 barcodetest[3514:1560798] THREAD WARNING: ['BarcodeScanner'] took '143.458984' ms. Plugin should use a background thread.
2016-11-02 12:50:14.585107 barcodetest[3514:1560798] WARNING: -[<AVCaptureVideoPreviewLayer: 0x7022c000> setOrientation:] is deprecated.  Please use AVCaptureConnection's -setVideoOrientation:
2016-11-02 12:50:14.704749 barcodetest[3514:1560798] [App] if we're in the real pre-commit handler we can't actually add any new fences due to CA restriction
2016-11-02 12:50:14.705175 barcodetest[3514:1560798] [App] if we're in the real pre-commit handler we can't actually add any new fences due to CA restriction

**Comment by cescd6** [comment] 2016-11-16 13:09
@embarbosa and @lucascdsilva I'm in the same situation:

On iOS I aim the red line to barcode, but nothing happens. It is not reading the Barcode type ITF (Interleaved2of5), with other formats like EAN_13 works fine. And Android instead works fine with ITF too.

Were you able to solve the problem? I attach the data to reproduce the error

**Cordova CLI version, cordova platform version and Plugin version**

```
$cordova --version
6.4.0

$cordova platforms
Installed platforms:
  android 5.1.1
  ios 4.1.1

$cordova plugin
...
phonegap-plugin-barcodescanner 6.0.3 "BarcodeScanner"
...
```
**Ionic framework**

My app is developed using the [Ionic framework v1.3] (http://ionicframework.com/) 

```
$ionic info
Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Framework Version: 1.3.0
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
ios-deploy version: 1.8.3 
ios-sim version: 3.0.0 
OS: Mac OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62 
```

**Bar code to reproduce this error**

![img_20161116_134421](https://cloud.githubusercontent.com/assets/5691846/20348483/eb1d05e4-ac05-11e6-8b9f-fb2ba6129a1a.jpg)

**My code**

```
        $cordovaBarcodeScanner
            .scan()
            .then(function (barcodeData) {
                $cordovaDialogs.alert("We got a barcode\n" +
                  "Result: " + barcodeData.text + "\n" +
                  "Format: " + barcodeData.format + "\n" +
                  "Cancelled: " + barcodeData.cancelled);
                $ionicLoading.hide();
                $scope.currentlyScanning = false;
                $scope.card.numero = barcodeData.text;
            }, function (error) {
                $ionicLoading.hide();
                $scope.currentlyScanning = false;
                $cordovaDialogs.alert(error, 'barcode Error', 'OK');
            },
            {
                "preferFrontCamera" : true, 
                "showFlipCameraButton" : true, 
                "prompt" : "Place a barcode inside the scan area", 
                "formats" : "ITF", 
                "orientation" : "landscape" 
            });
```

**Comment by embarbosa** [comment] 2016-11-16 13:27
@cescd6 Hello my friend,

Unfortunately I used another plugin that works well on iOS.
https://github.com/chen6516/cordova-zxing-portrait

A co-worker "forked" the repository above and "merged" the Android version of this repository.
https://github.com/jpfperondini/phonegap-plugin-barcodescanner

Sorry, I did not have time to solve it!
:(

**Comment by lucascdsilva** [comment] 2016-11-16 13:32
@cescd6 Hello,

 I still have not resolved, unfortunately it seems to be lack of support for this barcode encoding, we would need a help @wildabeast

**Comment by cescd6** [comment] 2016-11-18 11:19
@embarbosa You solution works fine in my situation!

Thanks you so much!

**Comment by lcustodio** [comment] 2017-01-30 14:09
@embarbosa, I've faced the same problem as described here and at #341.

The solution from @jpfperondini works nicely. 
Tested on iOS 10.1 and 10.2.

**Comment by robson83** [comment] 2018-01-09 17:01
@lcustodio @jpfperondini @cescd6 did you manage to make it work in iOS? I got it to scan the barcode correctly, but the numbers don't match with the numbers showing on the invoice.

Anything i'm missing?

**Comment by jcesarmobile** [comment] 2018-03-30 20:44
It's fixed now in master

**Closed by jcesarmobile** 2018-03-30 20:44 UTC
Labels: enhancement
