### ISSUE TITLE
Failed to build in Phonegap with cordova-plugin-facebook4

### ISSUE THREAD

**Issue by xale76** [phonegap/phonegap-plugin-barcodescanner#745] opened 2018-12-11 18:05 UTC
#### Cordova CLI version and cordova platform version

    cordova --version
    cordova platforms

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner

**Comment by jcesarmobile** [comment] 2018-12-11 18:07
Duplicate of https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/535

**Closed by jcesarmobile** 2018-12-11 18:07 UTC
