### ISSUE TITLE
Android: exit app when cancelled

### ISSUE THREAD

**Issue by Story5** [phonegap/phonegap-plugin-barcodescanner#647] opened 2018-04-15 15:29 UTC
### Expected Behaviour
    Return previous page when cancelled
### Actual Behaviour
    Exit app when cancelled
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
    Android 8.0.0
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
    OnePlus 3
#### Cordova CLI version and cordova platform version
    cordova 8.0.0
#### Plugin version
    7.1.0

**Comment by MatthiasBusch** [comment] 2018-04-24 13:32
I can confirm the same wrong behaviour on an OnePlus 5t

**Comment by jcesarmobile** [comment] 2018-04-28 22:03
Are you using Ionic?

**Comment by MatthiasBusch** [comment] 2018-04-30 07:00
No, I am using phonegap

**Comment by jcesarmobile** [comment] 2018-04-30 10:02
And any framework for the UI?

**Comment by MatthiasBusch** [comment] 2018-04-30 10:15
Yes, framework 7 actually, but i will test it soon with a blank app as well and provide feedback

**Comment by MatthiasBusch** [comment] 2018-04-30 12:49
Alright, it worked without the framework. After that I found out that they released a fix yesterday for it. So at least from my side this issue is resolved. Thanks!

**Comment by jcesarmobile** [comment] 2018-04-30 13:16
Yeah, that's what I thought, I asked about Ionic because I've seen the same problem there, but at it seems to be related to certain frameworks and not to Cordova/Phonegap I'll close the issue

**Closed by jcesarmobile** 2018-04-30 13:16 UTC
