### ISSUE TITLE
Add continuous scanning support

### ISSUE THREAD

**Issue by SunboX** [phonegap/phonegap-plugin-barcodescanner#122] opened 2015-12-07 12:29 UTC
Please add support for continuous scanning, so that the barcode scanner does not close after a successful scan.

This could work like this:

``` js
var scans = 0,
    messageTimeout;
cordova.plugins.barcodeScanner.continuousScan(
    function(result) {
        // This method will get triggered for every barcode found (continuously)
        clearTimeout(messageTimeout);
        cordova.plugins.barcodeScanner.message('Product found');
        setTimeout(function() {
            messageTimeout = cordova.plugins.barcodeScanner.message(null);
        }, 1000);
        if (++scans === 10) {
            cordova.plugins.barcodeScanner.hide();
        }
    },
    function(error) {
        clearTimeout(messageTimeout);
        cordova.plugins.barcodeScanner.message('Scanning failed: ' + error);
        setTimeout(function() {
            messageTimeout = cordova.plugins.barcodeScanner.message(null);
        }, 1000);
    }
);
```

**Comment by elewin** [comment] 2016-05-16 19:21
A work around I have used is to recursively call the scan method after every success until the user clicks cancel

**Comment by Giriton** [comment] 2016-07-08 08:50
I would also welcome this feature. It could for example "scan until user clicks done/back button" and then return results in array.. What do you think?

**Comment by abcd-ca** [comment] 2016-08-05 18:38
@Giriton I have just implemented such a workaround. I don't think it's quite as fast or elegant as just leaving the camera open but it does work. On iOS 9.3, the done button returns me to my Web UI, same with a Google Nexus 4 running Android 5.x. My "Samsung Galaxy Tab A" has a weird thing where if I tap the hardware back button to cancel, it closes the camera UI but also triggers a back call in the web ui, in my case either navigating me backwards or dismissing an open modal. So, I need to find a way for the back button, when in the camera UI, to not propagate to the web ui after dismissing the camera UI.

**Comment by carol-braileanu** [comment] 2016-12-17 02:46
I agree, continuous scanning is indeed needed for real-world scanning apps. Calling the scan() method recursively works, but it has some lag to it and it decreases performance. Any update on this issue?

**Comment by EddyVerbruggen** [comment] 2016-12-17 09:14
If anyone is willing to implement it: on Android we're using the same library as the NativeScript plugin which I've [added continuous scan support to already](https://github.com/EddyVerbruggen/nativescript-barcodescanner#function-scan-bulk--continuous-mode). All required changes to the native library are already in place, so it should be relatively straightforward to add this to the Cordova plugin as well.

On iOS the NativeScript plugin uses my custom library, not the same as the one used in the Cordova plugin, so it may be a little harder.

**Comment by fttx** [comment] 2017-07-02 11:50
+1

calling scan() recursively isn't a great solution

**Comment by macdonst** [comment] 2017-07-11 20:49
Duplicate of #69

**Closed by macdonst** 2017-07-11 20:49 UTC
Labels: duplicate

**Comment by houssem2101** [comment] 2017-07-20 14:50
+1

calling scan() recursively has some lag
