### ISSUE TITLE
Win 10 Pro N + Logitech c920 webcam = 0x80040154 - Class not registered

### ISSUE THREAD

**Issue by robert-crowell-gdit** [phonegap/phonegap-plugin-barcodescanner#367] opened 2016-11-14 20:16 UTC
### Expected Behaviour
Using phonegap-plugin-barcode scanner master branch, Win 10 x86 laptop with Logitech c920 web cam, expected to be able to scan barcode value using example code on main project page. Project does not say that Win10 + web cam are not usable combination with this plugin, therefore I expected the plugin to scan a barcode.

Not sure what I'm doing wrong, since I'm new to this.

### Actual Behaviour
Received Visual Studio debugger error for 'Class not registered':

'WWAHost.exe' (Script): Loaded 'Script Code (MSAppHost/3.0)'. 
'WWAHost.exe' (Script): Loaded 'Sourcemap (ms-appx-web://com.gdit.cordova.rounds/www/js\jquery.mobile-1.4.5\jquery.mobile-1.4.5.min.js)'. 
Exception is about to be caught by JavaScript library code at line 444, column 17 in ms-appx-web://com.gdit.cordova.rounds/www/plugins/phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy.js
0x80040154 - JavaScript runtime error: Class not registered

Exception is about to be caught by JavaScript library code at line 538, column 13 in ms-appx-web://com.gdit.cordova.rounds/www/plugins/phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy.js
0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'pause'

Line 444 in master branch references the Windows.Media object:

var captureSettings = new Windows.Media.Capture.MediaCaptureInitializationSettings();

So, I'm not sure if my laptop is missing essential software that the plugin requires, or what. Looked on MSDN's site for this object, but it never stated how to get it, if it's missing or not registered.

[https://msdn.microsoft.com/library/windows/apps/windows.media.capture.mediacaptureinitializationsettings]

### Reproduce Scenario (including but not limited to)
(see Steps to Reproduce)

#### Steps to Reproduce
Win 10 + web cam with proper drivers, Cordova, Git and example project setup.

cordova build

Open Windows 10 Visual Studio project "platforms \ windows \ CordovaApp.vs2013.sln", modified package.windows10.appxmanifest Capabilities to include "Webcam" support (assumed that it's needed, but error occurs either way), then start debugger.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Microsoft Windows 10 Pro N, x86 arch   v. 10.0.14393 Build 14393
Microsoft Visual Studio Community 2015  v. 14.0.25425.01 Update 3
Microsoft .NET Framework v. 4.6.01586

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
N/A

#### Cordova CLI version and cordova platform version

    cordova --version
            = 6.4.0

    cordova platforms
         = Installed platforms:
                     android 6.0.0
                     browser 4.1.0
                     windows 4.4.3

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner

= phonegap-plugin-barcodescanner 6.0.3 "BarcodeScanner"

#### Sample Code that illustrates the problem
Example code from the project's main page..

cordova.plugins.barcodeScanner.scan(
      function (result) {
          alert("We got a barcode\n" +
                "Result: " + result.text + "\n" +
                "Format: " + result.format + "\n" +
                "Cancelled: " + result.cancelled);
      },
      function (error) {
          alert("Scanning failed: " + error);
      },
      {
          "preferFrontCamera" : true, // iOS and Android
          "showFlipCameraButton" : true, // iOS and Android
          "prompt" : "Place a barcode inside the scan area", // supported on Android only
          "formats" : "QR_CODE,PDF_417", // default: all but PDF_417 and RSS_EXPANDED
          "orientation" : "landscape" // Android only (portrait|landscape), default unset so it rotates with the device
      }
   );

#### Logs taken while reproducing problem

'WWAHost.exe' (Script): Loaded 'Script Code (MSAppHost/3.0)'. 
'WWAHost.exe' (Script): Loaded 'Sourcemap (ms-appx-web://com.gdit.cordova.rounds/www/js\jquery.mobile-1.4.5\jquery.mobile-1.4.5.min.js)'. 
Exception is about to be caught by JavaScript library code at line 444, column 17 in ms-appx-web://com.gdit.cordova.rounds/www/plugins/phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy.js
0x80040154 - JavaScript runtime error: Class not registered

Exception is about to be caught by JavaScript library code at line 538, column 13 in ms-appx-web://com.gdit.cordova.rounds/www/plugins/phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy.js
0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'pause'

**Comment by daserge** [comment] 2016-11-15 11:45
@robert-crowell-gdit I've tested the plugin with USB web camera and could not reproduce the issue.
Could you please post the contents of `Extensions` tag of a generated appx/bundle AppxManifest.xml (it could be found in `platforms\windows\build\windows\Debug\x86\win10` or in `platforms\windows\AppPackages\...`)?

**Comment by daserge** [comment] 2016-11-15 11:52
Also - does it work differently if you deploy from CLI instead of Visual Studio?
`cordova run windows -- --arch=x86`
Note that you'll need to update to the master version of Windows platform to test this due to the DeviceCapability bug:
`cordova platform rm windows && cordova platform add https://github.com/apache/cordova-windows`

**Comment by robert-crowell-gdit** [comment] 2016-11-15 14:55
First I will address my existing windows platform v. 4.4.0 (before doing your recommended upgrade).

The Win10 Extensions (from location, "platforms\windows\build\windows\Debug\x86\win10"):
<Extensions>
    <Extension Category="windows.activatableClass.inProcessServer">
      <InProcessServer>
        <Path>CLRHost.dll</Path>
        <ActivatableClass ActivatableClassId="ZXing.BarcodeReader" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.QrCode.QRCodeWriter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.QrCode.QrCodeEncodingOptions" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.QrCode.Internal.QRCodeDecoderMetaData" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.QrCode.Internal.ErrorCorrectionLevel" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Datamatrix.Encoder.DefaultPlacement" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Datamatrix.DatamatrixEncodingOptions" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Datamatrix.DataMatrixWriter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Datamatrix.Internal.Version" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.ResultPoint" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Dimension" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Rendering.PixelDataRenderer" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Aztec.AztecResultMetadata" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Aztec.AztecEncodingOptions" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Aztec.AztecWriter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Result" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Common.EncodingOptions" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Common.BitArray" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Common.BitMatrix" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Common.DecodingOptions" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Common.BitSource" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Common.Detector.WhiteRectangleDetector" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Common.ReedSolomon.GenericGF" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.OneD.UPCAWriter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.OneD.Code128EncodingOptions" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.BarcodeWriter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.PDF417.PDF417Writer" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.PDF417.PDF417ResultMetadata" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.PDF417.PDF417EncodingOptions" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.PDF417.Internal.Dimensions" ThreadingModel="both" />
      </InProcessServer>
    </Extension>
  </Extensions>



I tried the application from Visual Studio in debugging mode, which gives me the error reported above.

I tried using your command line "cordova run windows -- --arch=x86", which installs and starts the application..  when I click my scan button to call a function that performs the example code function call "cordova.plugins.barcodeScanner.scan()"..  my application crashes with no output.


-------------------

Then, I performed your recommended command to update my windows platform from 4.4.0 TO --> "4.5.0-dev", which gives me the following Extensions section upon building.

<Extensions>
    <Extension Category="windows.activatableClass.inProcessServer">
      <InProcessServer>
        <Path>CLRHost.dll</Path>
        <ActivatableClass ActivatableClassId="ZXing.BarcodeReader" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.QrCode.QRCodeWriter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.QrCode.QrCodeEncodingOptions" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.QrCode.Internal.QRCodeDecoderMetaData" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.QrCode.Internal.ErrorCorrectionLevel" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Datamatrix.Encoder.DefaultPlacement" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Datamatrix.DatamatrixEncodingOptions" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Datamatrix.DataMatrixWriter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Datamatrix.Internal.Version" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.ResultPoint" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Dimension" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Rendering.PixelDataRenderer" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Aztec.AztecResultMetadata" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Aztec.AztecEncodingOptions" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Aztec.AztecWriter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Result" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Common.EncodingOptions" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Common.BitArray" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Common.BitMatrix" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Common.DecodingOptions" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Common.BitSource" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Common.Detector.WhiteRectangleDetector" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.Common.ReedSolomon.GenericGF" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.OneD.UPCAWriter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.OneD.Code128EncodingOptions" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.BarcodeWriter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.PDF417.PDF417Writer" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.PDF417.PDF417ResultMetadata" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.PDF417.PDF417EncodingOptions" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="ZXing.PDF417.Internal.Dimensions" ThreadingModel="both" />
      </InProcessServer>
    </Extension>
  </Extensions>


Then, I tried the application from Visual Studio in debugging mode, which gives me the same exact error reported above "Class not registered" on line 444.

'WWAHost.exe' (Script): Loaded 'Script Code (MSAppHost/3.0)'. 
'WWAHost.exe' (Script): Loaded 'Sourcemap (ms-appx-web://com.gdit.cordova.rounds/www/js\jquery.mobile-1.4.5\jquery.mobile-1.4.5.min.js)'. 
**Exception is about to be caught by JavaScript library code at line 444, column 17 in ms-appx-web://com.gdit.cordova.rounds/www/plugins/phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy.js
0x80040154 - JavaScript runtime error: Class not registered**

Exception is about to be caught by JavaScript library code at line 538, column 13 in ms-appx-web://com.gdit.cordova.rounds/www/plugins/phonegap-plugin-barcodescanner/src/windows/BarcodeScannerProxy.js
0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'pause'



Then, using the command "cordova run windows -- --arch=x86", it installs and starts the application. I click my scan button that calls my scan function that contains the example code from the this project's main page, but the application crashes yet again.  I get no output, so I can only assume that it's crashing on the same place.


I prefer the command line approach, but it provides zero feedback about why the application crashes, which is why I was trying to use Visual Studio's debugger in step mode to figure out the reason.

I have no idea what I'm doing wrong, PLEASE advise.

**Comment by robert-crowell-gdit** [comment] 2016-11-15 15:17
Since the line that is referenced points to "Windows.Media.blahblah"..  I check under my list of installed programs, and now I see that I don't have Windows Media player installed..  is that essential software?

I went to this website:  http://www.microsoft.com/en-us/download/windows-media-player-details.aspx

But received this page for Win 10 Pro N, x86:

Windows Media Player 
Windows Media Player is not compatible with your system. 
You are running Windows 10 32-bit. Although Windows Media Player will not run on your system, you can download Windows Media Player for other operating systems. 
Which version would you like to download? 
	Windows Media Player 11 for Windows XP
	Windows Media Player 11 for Windows XP (64-bit)

So, I seem to be missing the Windows media layer?  But then they say it's not compatible with x86 Win 10.. 

1. Is this the issue?
2. How can I fix this?

**Comment by robert-crowell-gdit** [comment] 2016-11-15 15:55
It seems I was missing a video player on my laptop..  either I mistakenly uninstalled it, thinking I wouldn't need it on a "compiler" laptop.. or it didn't install with my MSDN version of Win 10 Pro N, DVD ISO..

To document how I fixed this:

Microsoft Store has a "Movies & TV" application by Microsoft.  I installed that (which I did NOT have before).  After it's installation, it referred to a "Media Feature Pack for N version of Windows 10" that also had to be installed.

So, after installing the main movie application AND the media feature pack..  I can now play videos.. 

I retested my application and GET THE BARCODE SCANNING FEATURE!!!!!  :dancing_men:   :D

So sorry to have caused a problem for everyone, I didn't not know that the media layer would be required for Windows 10.  I also didn't realize that it was absent on my machine.

**Comment by daserge** [comment] 2016-11-16 08:06
@robert-crowell-gdit thanks for posting the results!
I've tried to reproduce the issue removing the Movies and TV and disabling entire Media Feature but unfortunately it still works for me.
I would be grateful if you could test the #368 (note that it might need the promise.done handler, which is not yet merged).

**Comment by robert-crowell-gdit** [comment] 2016-11-16 19:17
Removed Movies and TV,  can't find "Media Feature" to disable it..   cannot reproduce the original problem, so some background library / dll / code artifact-something must have been installed or patched into my system, as is.   Cannot reproduce issue anymore to test #368 as you requested....   maybe this was just a "one off" thing.

**Comment by daserge** [comment] 2016-11-16 19:48
`Media Feature` can be disabled in `Turn Windows features on or off`.

**Closed** 2016-11-17 11:55 UTC
