### ISSUE TITLE
Multiple dex files define issue when facebook4 plugin is present

### ISSUE THREAD

**Issue by wilsolutions** [phonegap/phonegap-plugin-barcodescanner#736] opened 2018-11-12 15:00 UTC
There's a conflict between barcodescanner and facebook4 plugin, both include the **xzing** library resulting in a error:
`com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lcom/google/zxing/oned/rss/expanded/decoders/AnyAIDecoder;`

The workaround is to use the Facebook SDK 4.25.0.

What can be done in the plugin in order to get it working when the facebook4 plugin is installed using the Facebook SDK 4.37.0?

**Comment by jcesarmobile** [comment] 2018-11-12 15:07
Closed as duplicate of https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/535

**Closed by jcesarmobile** 2018-11-12 15:07 UTC
