### ISSUE TITLE
[iOS] Scanning in landscape orientation ends on a blank screen

### ISSUE THREAD

**Issue by vvandens** [phonegap/phonegap-plugin-barcodescanner#402] opened 2017-01-19 10:01 UTC
Scanning in landscape orientation on an iOS device (iPhone or iPad) ends on a blank screen.

### Expected Behaviour
The cordova webview should be restored. This works perfectly on an Android device (tablet or phone).

### Actual Behaviour
The screen is blank. Rotating the device to portait restores the webview.

### Reproduce Scenario (including but not limited to)
Open the barcode scanner while in landscape orientation. Scan a barcode or cancel the scanning. The screen is blank.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 9.x
iOS 10.x

#### Cordova CLI version and cordova platform version
cordova --version : 6.3.1
cordova platforms : ios 4.3.1, android 5.2.2

#### Plugin version
phonegap-plugin-barcodescanner 6.0.5 "BarcodeScanner"

**Comment by RobinVerheijen** [comment] 2017-01-26 16:15
Same here, help wanted!

**Comment by tpdewolf** [comment] 2017-01-31 16:15
same here!

**Comment by tpdewolf** [comment] 2017-02-01 12:43
i have tried an alternative plugin (https://github.com/Scandit/barcodescanner-sdk-cordova) but the same problem occurred

cordova 6.4.0
cordova-ios 4.3.1

**Comment by jcesarmobile** [comment] 2017-02-01 12:49
The problem is cordova-plugin-statusbar, it's fixed in master branch, remove the plugin and install from github
`cordova plugin add https://github.com/apache/cordova-plugin-statusbar`

**Closed by jcesarmobile** 2017-02-01 12:49 UTC

**Comment by vvandens** [comment] 2017-02-01 13:09
Wow, thx @jcesarmobile !

**Comment by nbeguesse** [comment] 2017-02-28 16:00
You've saved the day, @jcesarmobile

**Comment by durasj** [comment] 2017-03-07 09:49
@jcesarmobile, thanks a lot. What is please the commit that fixes it on the _statusbar_ repo? Was it please already included in some version of _cordova-plugin-statusbar_? Depending on the master doesn't sound great. I would rather fix it to some version or at least commit (for the time being).

**Comment by jcesarmobile** [comment] 2017-03-07 09:55
There are a few commit's to fully fix the problem.
All Cordova core plugins are in release vote status right now, so they will be released soon if there are no problems spotted during the vote, maybe today or tomorrow. 
Stay tuned to the blog https://cordova.apache.org/blog/ or twitter https://twitter.com/apachecordova

**Comment by jcesarmobile** [comment] 2017-03-08 09:59
2.2.2 version of statusbar plugin has been released
