### ISSUE TITLE
On Android 4.4.2 immediately return cancelled status, but camera not dissapeared

### ISSUE THREAD

**Issue by ZoRDoK** [phonegap/phonegap-plugin-barcodescanner#27] opened 2015-07-07 13:55 UTC
Rarely return a scanned object. But if fall on start, not return anything even after success scan.

**Comment by surajpindoria** [comment] 2015-08-11 17:52
Hi @ZoRDoK, are you still seeing this issue? I am unable to reproduce.

**Comment by Deminetix** [comment] 2015-08-20 05:45
I believe this is related to https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/38

**Comment by sarangan12** [comment] 2016-05-05 23:34
This should be fixed with the latest telerik code merge. Resolving this issue. If you still find this issue, please reopen it

**Closed by sarangan12** 2016-05-05 23:34 UTC
Labels: bug
