### ISSUE TITLE
iOS returns more digits than Andriod

### ISSUE THREAD

**Issue by scottstout** [phonegap/phonegap-plugin-barcodescanner#487] opened 2017-06-15 17:47 UTC
### Expected Behaviour
If it is a UPC_A I think you are only supposed to get back 12 digits. On Android this is the case:

Result: 041220753772
Format: UPC_A
Cancelled: false

### Actual Behaviour

On iOS I get back 13 digits when scanning the same barcode:

We got a barcode
Result: 0041220753772
Format: UPC_A
Cancelled: 0

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Andriod (testing on old device 4.2.2, though others have tested with newer devices and it worked fine).
iOS (10.3.2)

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung Galaxy S III mini (but other have tested on newer devices)

#### Cordova CLI version and cordova platform version

    cordova --version 7.0.1
    cordova platforms 

#### Plugin version
Installed platforms:
  android 6.2.3
  ios 4.1.1
Available platforms:
  blackberry10 ~3.8.0 (deprecated)
  browser ~4.1.0
  webos ~3.7.0
  windows ~5.0.0

    cordova plugin version | grep phonegap-plugin-barcodescanner

phonegap-plugin-barcodescanner 6.0.6 "BarcodeScanner"

**Comment by macdonst** [comment] 2017-07-10 16:58
@scottstout yeah, that is weird. The UPC_A format is 12 digits. We'll look into why this is happening on iOS.

**Comment by macdonst** [comment] 2017-07-10 17:43
Duplicate of #364

**Closed by macdonst** 2017-07-10 17:43 UTC
Labels: bug, duplicate
