### ISSUE TITLE
Give user feedback when iOS barcodescanner is disabled in splitview or slideview mode

### ISSUE THREAD

**Issue by jonathanli2** [phonegap/phonegap-plugin-barcodescanner#542] opened 2017-09-12 15:39 UTC
### Expected Behaviour
iOS camera's video capture function only works in full screen mode, and if the application is in splitview or slideview mode, the video capture will automatically stop by iOS, and then resume again once the app is in full screen mode.

In Apple's AVCam sample app, when video capture is used, if the app enters splitview or slideview mode, the app will show an message to tell user the video capture stoped due to app is not full screen, and also ask user to change to full screen to continue using the video capture function. So user will not get confused why suddenly the video capture stops work.

The ios barcode scanner should also have the similar function, so when the app enters splitview or slideview mode, if barcode scanner is used, some kind message should show to user to tell them why the video capture stops working. 

### Actual Behaviour
In ios application, the bardcode video capture stops working without showing any information to user.

### Reproduce Scenario (including but not limited to)
using ipad in split view, or slide view with barcode scanner plugin

#### Steps to Reproduce
Create an ios application with barcode scanner plugin, run the app in ipad, put app into slideview or splitview while using video capture function, the video capture stops working without any message to user

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10.3.*

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Apple iPad Pro

#### Cordova CLI version and cordova platform version

    cordova --version
6.5.0 is used for testing

    cordova platforms
iOS

#### Plugin version
6.0.8
    
#### Sample Code that illustrates the problem
    cordova.plugins.barcodeScanner.scan( function (result) {
                                console.log("Scanner result: \n" +
                                            "text: " + result.text + "\n" +
                                            "format: " + result.format + "\n" +
                                            "cancelled: " + result.cancelled + "\n");        
                                return;
                                
                                }, function (error) {
                                    console.error("Scanning failed: " + error);
                                }
    );

**Comment by macdonst** [comment] 2017-09-15 15:33
Duplicate of #404

**Closed by macdonst** 2017-09-15 15:33 UTC
Labels: duplicate, enhancement, ios
