### ISSUE TITLE
Not working on android 6.0.1

### ISSUE THREAD

**Issue by ahsan154** [phonegap/phonegap-plugin-barcodescanner#564] opened 2017-10-27 14:03 UTC
### Expected Behaviour
It should worked like it is working on android 5, 7 and 8
### Actual Behaviour
reloading app after scanning code
### Reproduce Scenario (including but not limited to)
Install it and then open the app
#### Steps to Reproduce
Install it and then open the app
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0.1
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung J5, 2016
#### Cordova CLI version and cordova platform version
7.0.1, windows OS and android Mobile
    cordova --version
    cordova platforms

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner

#### Sample Code that illustrates the problem
No, i think it is a plugin issue, had used normal code given in the description

**Comment by jlchereau** [comment] 2017-10-27 14:45
Possibly the same as #565.

**Comment by macdonst** [comment] 2017-11-10 15:17
@ahsan154 a better reproduction scenario and some logs collected while running into the problem would really help us figure out what's going on.

**Comment by ahsan154** [comment] 2017-11-11 17:23
@jlchereau i don't think so it is similar to #565,  as plugin is opening barcode camera for me, but it is not scanning and refreshing page after detection instead of executing success/failure function.

**Comment by ahsan154** [comment] 2017-11-11 17:28
@macdonst a better reproduction scenario can be achieved:

1. create fresh android project
2. install plugin
3. paste the defualt code given on the documentation page
4. run on android 6.0.1 device
5. After scanning code neither success nor fail function gets execute instead it keeps reloading refreshing page.

**Comment by ahsan154** [comment] 2017-11-11 17:29
@macdonst a better reproduction scenario can be achieved:

1. create fresh android project
2. install plugin
3. paste the defualt code given on the documentation page
4. run on android 6.0.1 device
5. After scanning code neither success nor fail function gets execute instead it keeps reloading refreshing page.

**Comment by ahsan154** [comment] 2017-11-11 17:29
@macdonst a better reproduction scenario can be achieved:

1. create fresh android project
2. install plugin
3. paste the defualt code given on the documentation page
4. run on android 6.0.1 device
5. After scanning code neither success nor fail function gets execute instead it keeps reloading refreshing page.

**Comment by jcesarmobile** [comment] 2018-01-08 10:35
Closing as can't reproduce.
The sample code is working fine in my 6.0.1 Moto G, so it could be device specific.

**Closed by jcesarmobile** 2018-01-08 10:35 UTC
Labels: android, question
