### ISSUE TITLE
cordova build android - unable to find attribute android:fontVariationSettings and android:ttcIndex

### ISSUE THREAD

**Issue by bhandaribhumin** [phonegap/phonegap-plugin-barcodescanner#620] opened 2018-03-08 15:58 UTC
report issues : 

https://stackoverflow.com/questions/49162538/cordova-build-android-unable-to-find-attribute-androidfontvariationsettings-a

> FILE  :  project.properties
```
target=android-27
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.system.library.1=com.android.support:support-v13:26.+
cordova.system.library.2=me.leolin:ShortcutBadger:1.1.17@aar
cordova.system.library.3=com.google.firebase:firebase-messaging:11.6.2
cordova.gradle.include.1=phonegap-plugin-push/starter-push.gradle
cordova.gradle.include.2=phonegap-plugin-barcodescanner/campus-barcodescanner.gradle
```

**after remove barcode scanner build was successful**

**Comment by tylervz** [comment] 2018-03-08 22:37
This is a duplicate of #616

**Closed** 2018-03-08 23:23 UTC
